server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: kkc-backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kkc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
kundli-api:
  base-url: ${KUNDLI_API_BASE_URL:https://kundliapi.com}
  api-key: ka_free_c196f009a097a8bd061c7217a8d7ae9f8e440fd4c6067d58
  astro-data-path: ${KUNDLI_ASTRO_DATA_PATH:/api/astro/get_astro_data}